### ISSUE TITLE
AttributeError: 'list' object has no attribute 'sw'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rswarp#6]
A user writes:
> there occurs an error when I try to run the ionization sample from rswarp.
> What is the problem here:

```text
 ***  particle simulation package W3D running
Traceback (most recent call last):
  File "ionization.py", line 198, in <module>
    stept(100e-9)  # Simulate 100 ns
  File "/usr/local/lib/python2.7/dist-packages/warp/ctl.py", line 146, in stept
    step(1, 10)
  File "/usr/local/lib/python2.7/dist-packages/warp/ctl.py", line 96, in step
    command()
  File "/usr/local/lib/python2.7/dist-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "build/bdist.linux-x86_64/egg/rswarp/utilities/ionization.py", line 316, in generate

AttributeError: 'list' object has no attribute 'sw'
```

**Comment by cchall** [comment]
Index for the array containing macroparticle weight sw was not being correctly grabbed.
Fixed in 62a0962501c9f891d7727e77c1f56180ec87c64f.
